### ISSUE TITLE
Display PDF

### ISSUE THREAD

**Issue by kaaholst** [kaaholst/android-squeezer#673]
[Hi](url
![Screenshot_20201226-180548_Squeezer](https://user-images.githubusercontent.com/31885026/103156220-c62e5300-47a6-11eb-9f04-0786c483ba34.jpg)
![Screenshot_20201226-180555_Squeezer](https://user-images.githubusercontent.com/31885026/103156221-c6c6e980-47a6-11eb-807b-07d8527e8873.jpg)
![Screenshot_20201226-180605_Squeezer](https://user-images.githubusercontent.com/31885026/103156223-c75f8000-47a6-11eb-9195-80f516475e6c.jpg)

) Nick, Thank you for the great work on Squeezer. I have started to scan my CD booklets and I would like to raise the following feature request. When I click on 'Text files from music folders' the booklet PDF is listed as one of the available files (see 1). But when I click on 'booklet.pdf' (see 2) the error message (see 3) is displayed. I know this is not a 'text file', but nevertheless Android is able to display PDF content. Thanks for considering my feature request and again congratulations for this great app! Regards, Lucien[](url)

Original issue reported on github.com/nikclayton/android-squeezer by schmitzlucien on 2020-12-26T17:17:13Z

**Comment by kaaholst** [comment]
This issue is fixed in this [apk](https://drive.google.com/file/d/1xanOkuQpy36v2aw4OIm1brkCriPII6s_/view?usp=sharing).

You may continue to use this apk, it will automatically be updated when a new version is released. You can also revert to the version on Google Play, if you prefer to use an official version.

Thanks for the feedback.

**Comment by NicolasNicolass** [comment]
Thanks a lot. But unfortunately it doesn't work on my device: I still can't
open pdf.

Le jeu. 29 juin 2023 à 22:16, Kurt Aaholst ***@***.***> a
écrit :

**Comment by kaaholst** [comment]
I forgot to mention, this also requires a change on the LMS plugin which provides the link to the PDF. For Qobuz it's available from 2.15.3. For Music and Artist as shown above, I hope it will be available in the next version.

**Comment by NicolasNicolass** [comment]
OK, I'll try again with the next version, then. Because I mostly use a
local library (~1To of music on my NAS), rather than Qobuz...
I'll give you a feed back.
Thank you very much!

Le dim. 2 juil. 2023 à 22:58, Kurt Aaholst ***@***.***> a
écrit :

**Comment by kaaholst** [comment]
This is available in the latest versions, so closing this
